'use client'
import {useEffect,useState} from 'react'
import {supabaseBrowser} from '@/lib/supabase'

type Block={id:string,type:string,sort_order:number,data:any}
const defaults:any={hero:{title:'Tiêu đề hero',subtitle:'',image:'/assets/hero.jpg',cta:'Khám phá'},text:{heading:'Tiêu đề nội dung',body:'Nội dung…'},image:{url:'/assets/factory.jpg',alt:''},gallery:{images:[]},stats:{items:[{value:'600+',label:'HA'},{value:'100.000+',label:'XE/NĂM'}]},cta:{title:'Bạn cần tư vấn?',button:'Liên hệ ngay',url:'/contact'},products:{heading:'Sản phẩm nổi bật'},news:{heading:'Tin tức mới nhất'}}
export default function ContentBuilder({pageId}:{pageId:string}){
 const [blocks,setBlocks]=useState<Block[]>([]); const [saving,setSaving]=useState(false); const load=()=>supabaseBrowser().from('content_blocks').select('*').eq('page_id',pageId).order('sort_order').then(({data})=>setBlocks((data||[]) as Block[])); useEffect(()=>{load()},[])
 const add=async(type:string)=>{const {data,error}=await supabaseBrowser().from('content_blocks').insert({page_id:pageId,type,sort_order:blocks.length,data:defaults[type]}).select().single();if(!error&&data)setBlocks([...blocks,data as Block])}
 const patch=(id:string,data:any)=>setBlocks(bs=>bs.map(b=>b.id===id?{...b,data:{...b.data,...data}}:b))
 const save=async()=>{setSaving(true);for(const [i,b] of blocks.entries())await supabaseBrowser().from('content_blocks').update({sort_order:i,data:b.data,updated_at:new Date().toISOString()}).eq('id',b.id);setSaving(false);load()}
 const del=async(id:string)=>{await supabaseBrowser().from('content_blocks').delete().eq('id',id);load()}
 const move=(i:number,j:number)=>{if(j<0||j>=blocks.length)return;const x=[...blocks];const [b]=x.splice(i,1);x.splice(j,0,b);setBlocks(x)}
 return <section className="panel"><div className="panel-title"><div><span className="eyebrow">BLOCK BUILDER</span><h2>Kéo-thả nội dung trang</h2><p className="muted">Xây trang bằng các block, không cần viết code.</p></div><button className="btn primary" disabled={saving} onClick={save}>{saving?'Đang lưu…':'Lưu bố cục'}</button></div>
 <div className="builder-add">{Object.keys(defaults).map(t=><button key={t} className="btn secondary" onClick={()=>add(t)}>+ {t}</button>)}</div>
 <div className="block-list">{blocks.map((b,i)=><article key={b.id} className="builder-block"><div className="block-toolbar"><b>{i+1}. {b.type.toUpperCase()}</b><span/><button onClick={()=>move(i,i-1)}>↑</button><button onClick={()=>move(i,i+1)}>↓</button><button className="danger-text" onClick={()=>del(b.id)}>Xóa</button></div><BlockForm block={b} patch={patch}/></article>)}</div></section>
}
function BlockForm({block:b,patch}:{block:Block,patch:(id:string,data:any)=>void}){const d=b.data||{};switch(b.type){case'hero':return <div className="form-grid"><label>Tiêu đề<input value={d.title||''} onChange={e=>patch(b.id,{title:e.target.value})}/></label><label>Phụ đề<input value={d.subtitle||''} onChange={e=>patch(b.id,{subtitle:e.target.value})}/></label><label>Ảnh<input value={d.image||''} onChange={e=>patch(b.id,{image:e.target.value})}/></label><label>CTA<input value={d.cta||''} onChange={e=>patch(b.id,{cta:e.target.value})}/></label></div>;case'text':return <div className="form-grid"><label>Tiêu đề<input value={d.heading||''} onChange={e=>patch(b.id,{heading:e.target.value})}/></label><label>Nội dung<textarea rows={5} value={d.body||''} onChange={e=>patch(b.id,{body:e.target.value})}/></label></div>;case'image':return <div className="form-grid"><label>URL ảnh<input value={d.url||''} onChange={e=>patch(b.id,{url:e.target.value})}/></label><label>Alt<input value={d.alt||''} onChange={e=>patch(b.id,{alt:e.target.value})}/></label></div>;case'stats':return <div><p className="muted">JSON thống kê</p><textarea rows={5} value={JSON.stringify(d.items||[],null,2)} onChange={e=>{try{patch(b.id,{items:JSON.parse(e.target.value)})}catch{}}}/></div>;case'cta':return <div className="form-grid"><label>Tiêu đề<input value={d.title||''} onChange={e=>patch(b.id,{title:e.target.value})}/></label><label>Nút<input value={d.button||''} onChange={e=>patch(b.id,{button:e.target.value})}/></label><label>URL<input value={d.url||''} onChange={e=>patch(b.id,{url:e.target.value})}/></label></div>;default:return <label>Tiêu đề<input value={d.heading||''} onChange={e=>patch(b.id,{heading:e.target.value})}/></label>}}
